### ISSUE TITLE
group session unhandled exception

### ISSUE THREAD

**Issue by woinbo** [MixinNetwork/libsignal_protocol_dart#36]
while running `groupSession()` function complier five error: 
```terminal
Unhandled exception:
NoSessionException - No key state in record!
#0      GroupCipher.encrypt (package:libsignal_protocol_dart/src/groups/GroupCipher.dart:37:7)
#1      groupSessioin (package:signaltest/main.dart:92:16)
#2      main (package:signaltest/main.dart:8:3)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

please help!!!

**Comment by Tougee** [comment]
Check here https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/test/groups/group_cipher_test.dart#L57
