### ISSUE TITLE
Failed to load dynamic library (Flutter app)

### ISSUE THREAD

**Issue by xni06** [MixinNetwork/libsignal_protocol_dart#4]
By cut'n pasting your example code into a default Flutter app, it fails as it is unable to load the dynamic library. I would appreciate it if you could advise as to what additional steps I should take beyond what is stated in https://pub.dev/packages/libsignal_protocol_dart/install

Thanks.

```
flutter run
Launching lib/main.dart on Pixel in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        30.4s
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                        25.1s
I/flutter (30950): install
E/flutter (30950): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "/main.dartlibgodart.so" not found)
E/flutter (30950): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
E/flutter (30950): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter (30950): #2      dlopenPlatformSpecific (package:libsignal_protocol_dart/src/ecc/dylib_utils.dart:16:29)
E/flutter (30950): #3      libsignal (package:libsignal_protocol_dart/src/ecc/SignCurve25519.dart:23:5)
E/flutter (30950): #4      libsignal (package:libsignal_protocol_dart/src/ecc/SignCurve25519.dart:22:7)
E/flutter (30950): #5      sign (package:libsignal_protocol_dart/src/ecc/SignCurve25519.dart:28:24)
E/flutter (30950): #6      Curve.calculateSignature (package:libsignal_protocol_dart/src/ecc/Curve.dart:103:14)
E/flutter (30950): #7      KeyHelper.generateSignedPreKey (package:libsignal_protocol_dart/src/util/KeyHelper.dart:46:27)
E/flutter (30950): #8      install (package:example3/main.dart:18:32)
E/flutter (30950): #9      main (package:example3/main.dart:7:3)
E/flutter (30950): #10     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (30950): #11     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (30950): #12     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (30950): #13     _runZoned (dart:async/zone.dart:1619:10)
E/flutter (30950): #14     runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (30950): #15     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (30950): #16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (30950): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/rhisiart/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rhisiart/Library/android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = /Users/rhisiart/Library/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (1 available)
    • Pixel • 192.168.1.65:5555 • android-arm64 • Android 10 (API 29)

• No issues found!
```

**pubspec.yaml**
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  libsignal_protocol_dart: ^0.0.2

dependency_overrides:
  collection: ^1.14.12
```

**main.dart**
```dart
void main() {
  install();
  runApp(MyApp());
}

// This is a cut'n paste from your example code
void install() {
  debugPrint('install');
  var identityKeyPair = KeyHelper.generateIdentityKeyPair();
  var registerationId = KeyHelper.generateRegistrationId(false);

  var preKeys = KeyHelper.generatePreKeys(0, 110);

  ... and so on
```

**Comment by crossle** [comment]
https://github.com/MixinNetwork/libsignal_protocol_dart/issues/1

**Comment by Tougee** [comment]
This will be fixed in the next release after this https://github.com/MixinNetwork/libsignal_protocol_dart/pull/5 merge.
